ANDROID: rust_binder: Enable and fix missing-prototypes errors
Enable -Wmissing-prototypes and -Wmissing-declarations for the rust
binder and fix the newly flagged issues accordingly.

Fixes several missing-prototypes warnings such as:

  [...]
  common/drivers/android/binder/rust_binderfs.c:95:6: error: no previous prototype for function 'is_rust_binderfs_device' [-Werror,-Wmissing-prototypes]
     95 | bool is_rust_binderfs_device(const struct inode *inode)
        |      ^
  common/drivers/android/binder/rust_binderfs.c:95:1: note: declare 'static' if the function is not intended to be used outside of this translation unit
     95 | bool is_rust_binderfs_device(const struct inode *inode)
        | ^
        | static
  [...]
  5 errors generated.

Bug: 425609355
Change-Id: I4f9f0b8b17795cb88d0a4c5816081598dd98be95
Signed-off-by: Jacky Liu <qsliu@google.com>
[cmllamas: minor stylistic changes]
Signed-off-by: Carlos Llamas <cmllamas@google.com>